name: issues event
on: issues
jobs:
  issue-event:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Output of Github Event
        run: echo "${{ toJson(github.event) }}"
      - name: Handle issues event
        run: |
         'echo Issue event triggered: ${{ github.event.issue.title }}'
         'echo Issue event triggered: ${{ github.event.issue.body }}'
         'echo Issue Number: ${{ github.event.issue.number }}'
